media: 
  input: docs/assets
  output: ../../assets
content:
  - name: posts
    label: Posts
    type: collection
    path: docs/blog/posts
    filename: "{fields.date}.md"
    view:
      fields: [ body, date ]
    fields:
      - {name: date, label: Date, type: date }
      - {name: body, label: Body, type: rich-text }
    